title: "Musikgesellschaft Rumisberg"
default_lang: de
author:
  name: Nicholas Krebs
  email: "nicholas@nicholas-krebs.ch"
taxonomies:
  - category
  - tag
metadata:
  description: "Dies ist die Website der Musikgesellschaft Rumisberg"
summary:
  enabled: true
  format: short
  size: 300
  delimiter: "==="
redirects: null
routes: null
blog:
  route: /blog
